<../../mkconfig

TARG=\
	run.dis\

SYSMODULES=\
	arg.m\
	bufio.m\
	daytime.m\
	draw.m\
	keyboard.m\
	names.m\
	plumbmsg.m\
	readdir.m\
	sh.m\
	string.m\
	sys.m\
	tk.m\
	tkclient.m\
	wait.m\

DISBIN=$ROOT/dis/wm

<$ROOT/mkfiles/mkdis
